# Generated by Django 4.2.5 on 2023-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomainPakar', '0002_alter_pasien_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='GejalaPasien',
            field=models.ManyToManyField(blank=True, to='DomainPakar.gejala'),
        ),
    ]
